name: ai_desensitization
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1


environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_rust_bridge: 2.8.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.5.0
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  rust_lib_ai_desensitization:
    path: rust_builder
  window_manager: ^0.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

