// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/nlp.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'nlp/tags.dart';
import 'nlp/words.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.8.0';

  @override
  int get rustContentHash => -1103566208;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_ai_desensitization',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiNlpAddSegmentWord({
    required String word,
    required BigInt freq,
    required String tag,
  });

  String crateApiNlpGetTagName({required Tag tag});

  Future<Words> crateApiNlpGetWordSegResult({required String text});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiNlpMaskEntities({
    required String text,
    required OperationConfig cfg,
  });

  Future<Words> crateApiNlpMaskEntitiesWithTags({
    required String text,
    required OperationConfig cfg,
  });

  Future<String> crateApiNlpRemoveEntities({
    required String text,
    required OperationConfig cfg,
  });

  Future<Words> crateApiNlpRemoveEntitiesWithTags({
    required String text,
    required OperationConfig cfg,
  });

  Future<String> crateApiNlpReplaceEntities({
    required String text,
    required OperationConfig cfg,
  });

  Future<Words> crateApiNlpReplaceEntitiesWithTags({
    required String text,
    required OperationConfig cfg,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiNlpAddSegmentWord({
    required String word,
    required BigInt freq,
    required String tag,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(word, serializer);
          sse_encode_usize(freq, serializer);
          sse_encode_String(tag, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpAddSegmentWordConstMeta,
        argValues: [word, freq, tag],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpAddSegmentWordConstMeta => const TaskConstMeta(
    debugName: "add_segment_word",
    argNames: ["word", "freq", "tag"],
  );

  @override
  String crateApiNlpGetTagName({required Tag tag}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_tag(tag, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpGetTagNameConstMeta,
        argValues: [tag],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpGetTagNameConstMeta =>
      const TaskConstMeta(debugName: "get_tag_name", argNames: ["tag"]);

  @override
  Future<Words> crateApiNlpGetWordSegResult({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_words,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpGetWordSegResultConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpGetWordSegResultConstMeta =>
      const TaskConstMeta(debugName: "get_word_seg_result", argNames: ["text"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiNlpMaskEntities({
    required String text,
    required OperationConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_box_autoadd_operation_config(cfg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpMaskEntitiesConstMeta,
        argValues: [text, cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpMaskEntitiesConstMeta => const TaskConstMeta(
    debugName: "mask_entities",
    argNames: ["text", "cfg"],
  );

  @override
  Future<Words> crateApiNlpMaskEntitiesWithTags({
    required String text,
    required OperationConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_box_autoadd_operation_config(cfg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_words,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpMaskEntitiesWithTagsConstMeta,
        argValues: [text, cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpMaskEntitiesWithTagsConstMeta =>
      const TaskConstMeta(
        debugName: "mask_entities_with_tags",
        argNames: ["text", "cfg"],
      );

  @override
  Future<String> crateApiNlpRemoveEntities({
    required String text,
    required OperationConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_box_autoadd_operation_config(cfg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpRemoveEntitiesConstMeta,
        argValues: [text, cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpRemoveEntitiesConstMeta => const TaskConstMeta(
    debugName: "remove_entities",
    argNames: ["text", "cfg"],
  );

  @override
  Future<Words> crateApiNlpRemoveEntitiesWithTags({
    required String text,
    required OperationConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_box_autoadd_operation_config(cfg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_words,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpRemoveEntitiesWithTagsConstMeta,
        argValues: [text, cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpRemoveEntitiesWithTagsConstMeta =>
      const TaskConstMeta(
        debugName: "remove_entities_with_tags",
        argNames: ["text", "cfg"],
      );

  @override
  Future<String> crateApiNlpReplaceEntities({
    required String text,
    required OperationConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_box_autoadd_operation_config(cfg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpReplaceEntitiesConstMeta,
        argValues: [text, cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpReplaceEntitiesConstMeta => const TaskConstMeta(
    debugName: "replace_entities",
    argNames: ["text", "cfg"],
  );

  @override
  Future<Words> crateApiNlpReplaceEntitiesWithTags({
    required String text,
    required OperationConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_box_autoadd_operation_config(cfg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_words,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNlpReplaceEntitiesWithTagsConstMeta,
        argValues: [text, cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNlpReplaceEntitiesWithTagsConstMeta =>
      const TaskConstMeta(
        debugName: "replace_entities_with_tags",
        argNames: ["text", "cfg"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  OperationConfig dco_decode_box_autoadd_operation_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_operation_config(raw);
  }

  @protected
  Tag dco_decode_box_autoadd_tag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tag(raw);
  }

  @protected
  WordcutTag dco_decode_box_autoadd_wordcut_tag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_wordcut_tag(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Word> dco_decode_list_word(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_word).toList();
  }

  @protected
  OperationConfig dco_decode_operation_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OperationConfig(
      i18N: dco_decode_String(arr[0]),
      type: dco_decode_usize(arr[1]),
      params: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  OtherTags dco_decode_other_tags(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OtherTags.values[raw as int];
  }

  @protected
  Tag dco_decode_tag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Tag_Wordcut(dco_decode_box_autoadd_wordcut_tag(raw[1]));
      case 1:
        return Tag_Others(dco_decode_other_tags(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Word dco_decode_word(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Word(word: dco_decode_String(arr[0]), tag: dco_decode_tag(arr[1]));
  }

  @protected
  WordcutTag dco_decode_wordcut_tag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return WordcutTag_N();
      case 1:
        return WordcutTag_Nr();
      case 2:
        return WordcutTag_Ns();
      case 3:
        return WordcutTag_Nt();
      case 4:
        return WordcutTag_Nz();
      case 5:
        return WordcutTag_V();
      case 6:
        return WordcutTag_Vd();
      case 7:
        return WordcutTag_Vn();
      case 8:
        return WordcutTag_A();
      case 9:
        return WordcutTag_Ad();
      case 10:
        return WordcutTag_An();
      case 11:
        return WordcutTag_D();
      case 12:
        return WordcutTag_Dg();
      case 13:
        return WordcutTag_R();
      case 14:
        return WordcutTag_Rr();
      case 15:
        return WordcutTag_Rz();
      case 16:
        return WordcutTag_M();
      case 17:
        return WordcutTag_Mq();
      case 18:
        return WordcutTag_Q();
      case 19:
        return WordcutTag_P();
      case 20:
        return WordcutTag_C();
      case 21:
        return WordcutTag_U();
      case 22:
        return WordcutTag_Ug();
      case 23:
        return WordcutTag_Us();
      case 24:
        return WordcutTag_E();
      case 25:
        return WordcutTag_O();
      case 26:
        return WordcutTag_S();
      case 27:
        return WordcutTag_X(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  Words dco_decode_words(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Words(field0: dco_decode_list_word(arr[0]));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  OperationConfig sse_decode_box_autoadd_operation_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_operation_config(deserializer));
  }

  @protected
  Tag sse_decode_box_autoadd_tag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tag(deserializer));
  }

  @protected
  WordcutTag sse_decode_box_autoadd_wordcut_tag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_wordcut_tag(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Word> sse_decode_list_word(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Word>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_word(deserializer));
    }
    return ans_;
  }

  @protected
  OperationConfig sse_decode_operation_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_i18N = sse_decode_String(deserializer);
    var var_type = sse_decode_usize(deserializer);
    var var_params = sse_decode_list_String(deserializer);
    return OperationConfig(i18N: var_i18N, type: var_type, params: var_params);
  }

  @protected
  OtherTags sse_decode_other_tags(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return OtherTags.values[inner];
  }

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_wordcut_tag(deserializer);
        return Tag_Wordcut(var_field0);
      case 1:
        var var_field0 = sse_decode_other_tags(deserializer);
        return Tag_Others(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  Word sse_decode_word(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_word = sse_decode_String(deserializer);
    var var_tag = sse_decode_tag(deserializer);
    return Word(word: var_word, tag: var_tag);
  }

  @protected
  WordcutTag sse_decode_wordcut_tag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return WordcutTag_N();
      case 1:
        return WordcutTag_Nr();
      case 2:
        return WordcutTag_Ns();
      case 3:
        return WordcutTag_Nt();
      case 4:
        return WordcutTag_Nz();
      case 5:
        return WordcutTag_V();
      case 6:
        return WordcutTag_Vd();
      case 7:
        return WordcutTag_Vn();
      case 8:
        return WordcutTag_A();
      case 9:
        return WordcutTag_Ad();
      case 10:
        return WordcutTag_An();
      case 11:
        return WordcutTag_D();
      case 12:
        return WordcutTag_Dg();
      case 13:
        return WordcutTag_R();
      case 14:
        return WordcutTag_Rr();
      case 15:
        return WordcutTag_Rz();
      case 16:
        return WordcutTag_M();
      case 17:
        return WordcutTag_Mq();
      case 18:
        return WordcutTag_Q();
      case 19:
        return WordcutTag_P();
      case 20:
        return WordcutTag_C();
      case 21:
        return WordcutTag_U();
      case 22:
        return WordcutTag_Ug();
      case 23:
        return WordcutTag_Us();
      case 24:
        return WordcutTag_E();
      case 25:
        return WordcutTag_O();
      case 26:
        return WordcutTag_S();
      case 27:
        var var_field0 = sse_decode_String(deserializer);
        return WordcutTag_X(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  Words sse_decode_words(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_word(deserializer);
    return Words(field0: var_field0);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_operation_config(
    OperationConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_operation_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tag(Tag self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tag(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_wordcut_tag(
    WordcutTag self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wordcut_tag(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_word(List<Word> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_word(item, serializer);
    }
  }

  @protected
  void sse_encode_operation_config(
    OperationConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.i18N, serializer);
    sse_encode_usize(self.type, serializer);
    sse_encode_list_String(self.params, serializer);
  }

  @protected
  void sse_encode_other_tags(OtherTags self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Tag_Wordcut(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_wordcut_tag(field0, serializer);
      case Tag_Others(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_other_tags(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_word(Word self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.word, serializer);
    sse_encode_tag(self.tag, serializer);
  }

  @protected
  void sse_encode_wordcut_tag(WordcutTag self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case WordcutTag_N():
        sse_encode_i_32(0, serializer);
      case WordcutTag_Nr():
        sse_encode_i_32(1, serializer);
      case WordcutTag_Ns():
        sse_encode_i_32(2, serializer);
      case WordcutTag_Nt():
        sse_encode_i_32(3, serializer);
      case WordcutTag_Nz():
        sse_encode_i_32(4, serializer);
      case WordcutTag_V():
        sse_encode_i_32(5, serializer);
      case WordcutTag_Vd():
        sse_encode_i_32(6, serializer);
      case WordcutTag_Vn():
        sse_encode_i_32(7, serializer);
      case WordcutTag_A():
        sse_encode_i_32(8, serializer);
      case WordcutTag_Ad():
        sse_encode_i_32(9, serializer);
      case WordcutTag_An():
        sse_encode_i_32(10, serializer);
      case WordcutTag_D():
        sse_encode_i_32(11, serializer);
      case WordcutTag_Dg():
        sse_encode_i_32(12, serializer);
      case WordcutTag_R():
        sse_encode_i_32(13, serializer);
      case WordcutTag_Rr():
        sse_encode_i_32(14, serializer);
      case WordcutTag_Rz():
        sse_encode_i_32(15, serializer);
      case WordcutTag_M():
        sse_encode_i_32(16, serializer);
      case WordcutTag_Mq():
        sse_encode_i_32(17, serializer);
      case WordcutTag_Q():
        sse_encode_i_32(18, serializer);
      case WordcutTag_P():
        sse_encode_i_32(19, serializer);
      case WordcutTag_C():
        sse_encode_i_32(20, serializer);
      case WordcutTag_U():
        sse_encode_i_32(21, serializer);
      case WordcutTag_Ug():
        sse_encode_i_32(22, serializer);
      case WordcutTag_Us():
        sse_encode_i_32(23, serializer);
      case WordcutTag_E():
        sse_encode_i_32(24, serializer);
      case WordcutTag_O():
        sse_encode_i_32(25, serializer);
      case WordcutTag_S():
        sse_encode_i_32(26, serializer);
      case WordcutTag_X(field0: final field0):
        sse_encode_i_32(27, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_words(Words self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_word(self.field0, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
