// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'jieba_tag.freezed.dart';

@freezed
sealed class JiebaTag with _$JiebaTag {
  const JiebaTag._();

  const factory JiebaTag.n() = JiebaTag_N;
  const factory JiebaTag.nr() = JiebaTag_Nr;
  const factory JiebaTag.ns() = JiebaTag_Ns;
  const factory JiebaTag.nt() = JiebaTag_Nt;
  const factory JiebaTag.nz() = JiebaTag_Nz;
  const factory JiebaTag.v() = JiebaTag_V;
  const factory JiebaTag.vd() = JiebaTag_Vd;
  const factory JiebaTag.vn() = JiebaTag_Vn;
  const factory JiebaTag.a() = JiebaTag_A;
  const factory JiebaTag.ad() = JiebaTag_Ad;
  const factory JiebaTag.an() = JiebaTag_An;
  const factory JiebaTag.d() = JiebaTag_D;
  const factory JiebaTag.dg() = JiebaTag_Dg;
  const factory JiebaTag.r() = JiebaTag_R;
  const factory JiebaTag.rr() = JiebaTag_Rr;
  const factory JiebaTag.rz() = JiebaTag_Rz;
  const factory JiebaTag.m() = JiebaTag_M;
  const factory JiebaTag.mq() = JiebaTag_Mq;
  const factory JiebaTag.q() = JiebaTag_Q;
  const factory JiebaTag.p() = JiebaTag_P;
  const factory JiebaTag.c() = JiebaTag_C;
  const factory JiebaTag.u() = JiebaTag_U;
  const factory JiebaTag.ug() = JiebaTag_Ug;
  const factory JiebaTag.us() = JiebaTag_Us;
  const factory JiebaTag.e() = JiebaTag_E;
  const factory JiebaTag.o() = JiebaTag_O;
  const factory JiebaTag.s() = JiebaTag_S;
  const factory JiebaTag.x(String field0) = JiebaTag_X;
}
